# @package experiment.config.monty_config.sensor_modules

sensor_module_0:
  _target_: tbp.monty.frameworks.models.sensor_modules.CameraSM
  sensor_module_id: patch_0
  features:
  - pose_vectors
  - pose_fully_defined
  - on_object
  - object_coverage
  - min_depth
  - mean_depth
  - hsv
  - principal_curvatures_log
  delta_thresholds:
    on_object: 0
    n_steps: 20
    hsv:
    - 0.1
    - 0.1
    - 0.1
    pose_vectors: ${np.list_eval:[np.pi / 4, np.pi * 2, np.pi * 2]}
    principal_curvatures_log:
    - 2
    - 2
    distance: 0.01
  save_raw_obs: true
sensor_module_1:
  _target_: tbp.monty.frameworks.models.sensor_modules.CameraSM
  sensor_module_id: patch_1
  features:
  - pose_vectors
  - pose_fully_defined
  - on_object
  - object_coverage
  - hsv
  - principal_curvatures_log
  delta_thresholds:
    on_object: 0
    n_steps: 100
    hsv:
    - 0.2
    - 0.2
    - 0.2
    pose_vectors: ${np.list_eval:[np.pi / 4, np.pi * 2, np.pi * 2]}
    principal_curvatures_log:
    - 4
    - 4
    distance: 0.05
  save_raw_obs: true
sensor_module_2:
  _target_: tbp.monty.frameworks.models.sensor_modules.Probe
  sensor_module_id: view_finder
  save_raw_obs: true
