# @package experiment.config.monty_config.sensor_modules

sensor_module_0:
  _target_: tbp.monty.frameworks.models.sensor_modules.CameraSM
  sensor_module_id: patch_0
  features: ${constants.default_sensor_features}
  save_raw_obs: false
  delta_thresholds:
    on_object: 0
    distance: 0.01
  noise_params: ${constants.default_all_noise_params}
sensor_module_1:
  _target_: tbp.monty.frameworks.models.sensor_modules.CameraSM
  sensor_module_id: patch_1
  features: ${constants.default_sensor_features}
  save_raw_obs: false
  delta_thresholds:
    on_object: 0
    distance: 0.01
  noise_params: ${constants.default_all_noise_params}
sensor_module_2:
  _target_: tbp.monty.frameworks.models.sensor_modules.CameraSM
  sensor_module_id: patch_2
  features: ${constants.default_sensor_features}
  save_raw_obs: false
  delta_thresholds:
    on_object: 0
    distance: 0.01
  noise_params: ${constants.default_all_noise_params}
sensor_module_3:
  _target_: tbp.monty.frameworks.models.sensor_modules.CameraSM
  sensor_module_id: patch_3
  features: ${constants.default_sensor_features}
  save_raw_obs: false
  delta_thresholds:
    on_object: 0
    distance: 0.01
  noise_params: ${constants.default_all_noise_params}
sensor_module_4:
  _target_: tbp.monty.frameworks.models.sensor_modules.CameraSM
  sensor_module_id: patch_4
  features: ${constants.default_sensor_features}
  save_raw_obs: false
  delta_thresholds:
    on_object: 0
    distance: 0.01
  noise_params: ${constants.default_all_noise_params}
sensor_module_5:
  _target_: tbp.monty.frameworks.models.salience.sensor_module.SalienceSM
  sensor_module_id: view_finder
  save_raw_obs: true
