# @package experiment.config.monty_config.sensor_modules

sensor_module_0:
  _target_: tbp.monty.frameworks.models.sensor_modules.CameraSM
  sensor_module_id: patch
  features:
  - pose_vectors
  - pose_fully_defined
  - on_object
  - object_coverage
  - hsv
  - principal_curvatures_log
  delta_thresholds:
    on_object: 0
    n_steps: 20
    hsv:
    - 0.1
    - 0.1
    - 0.1
    pose_vectors: ${np.list_eval:[np.pi / 4, np.pi * 2, np.pi * 2]}
    principal_curvatures_log:
    - 2
    - 2
    distance: 0.01
  save_raw_obs: false
sensor_module_1:
  _target_: tbp.monty.frameworks.models.salience.sensor_module.SalienceSM
  sensor_module_id: view_finder
  save_raw_obs: false
  salience_strategy:
    _target_: tbp.monty.frameworks.models.salience.strategies.vocus2.Vocus2.from_config
    config:
      _target_: tbp.monty.frameworks.models.salience.strategies.vocus2.vocus2.Vocus2SalienceConfig
      center_sigma: 1.0
      surround_sigma: 6.5
      n_scales: 2
      max_octaves: 5
      use_depth: true
      use_orientation: false
