# @package experiment.config.monty_config.sensor_modules

sensor_module_0:
  _target_: tbp.monty.frameworks.models.sensor_modules.CameraSM
  features:
  - pose_vectors
  - pose_fully_defined
  - on_object
  - object_coverage
  - min_depth
  - mean_depth
  - hsv
  - principal_curvatures
  - principal_curvatures_log
  sensor_module_id: patch
  save_raw_obs: false
  delta_thresholds:
    on_object: 0
    distance: 0.01
  is_surface_sm: true
  noise_params:
    features:
      pose_vectors: 2 # rotate by random degrees along xyz
      hsv: 0.1 # add gaussian noise with 0.1 std
      principal_curvatures_log: 0.1
      pose_fully_defined: 0.01 # flip bool in 1% of cases
    location: 0.002 # add gaussian noise with 0.002 std
sensor_module_1:
  _target_: tbp.monty.frameworks.models.sensor_modules.Probe
  sensor_module_id: view_finder
  save_raw_obs: true
