# @package experiment.config.monty_config.sensor_modules

sensor_module_0:
  _target_: tbp.monty.frameworks.models.sensor_modules.CameraSM
  sensor_module_id: patch
  features:
  - on_object
  - object_coverage
  - rgba
  - hsv
  - pose_vectors
  - principal_curvatures
  - principal_curvatures_log
  - gaussian_curvature
  - mean_curvature
  - gaussian_curvature_sc
  - mean_curvature_sc
  save_raw_obs: false
sensor_module_1:
  _target_: tbp.monty.frameworks.models.sensor_modules.Probe
  sensor_module_id: view_finder
  save_raw_obs: false
