# @package experiment.config.monty_config.motor_system_config.policy_selector.policy

defaults:
  - action_sampler: uniform_dist

_target_: tbp.monty.frameworks.models.motor_policies.BasePolicy
agent_id: agent_id_0
