# @package experiment.config.monty_config.motor_system_config.policy_selector.policy

defaults:
  - action_sampler: constant_dist

_target_: tbp.monty.frameworks.models.motor_policies.NaiveScanPolicy
use_goal_driven_actions: false
agent_id: agent_id_0
fixed_amount: 10
