_target_: tbp.monty.frameworks.models.motor_policies.SurfacePolicyCurvatureInformed
action_sampler:
  _target_: tbp.monty.frameworks.actions.action_samplers.ConstantSampler
  actions:
  - ${monty.class:tbp.monty.frameworks.actions.actions.MoveForward}
  - ${monty.class:tbp.monty.frameworks.actions.actions.MoveTangentially}
  - ${monty.class:tbp.monty.frameworks.actions.actions.OrientHorizontal}
  - ${monty.class:tbp.monty.frameworks.actions.actions.OrientVertical}
desired_object_distance: 0.025
alpha: 0.1
pc_alpha: 0.5
# For a description of the below step parameters, see the class
# SurfacePolicyCurvatureInformed
max_pc_bias_steps: 32
min_general_steps: 8
min_heading_steps: 12
use_goal_driven_actions: false
agent_id: agent_id_0
