# @package experiment.config.monty_config.motor_system_config.policy_selector.policy

_target_: tbp.monty.frameworks.models.motor_policies.PredefinedPolicy
agent_id: agent_id_0
file_name: ${path.tests:unit/resources/fixed_test_actions.jsonl}
