# @package experiment.config

do_eval: true
eval_env_interface_args:
  parent_to_child_mapping: null
  object_names:
  - mug
  - e_cups
  - knife
  - fork
  - spoon
  - c_cups
  - d_cups
  - cracker_box
  - sugar_box
  - pudding_box
  object_init_sampler:
    _target_: tbp.monty.frameworks.environments.object_init_samplers.Predefined
    rotations: ${constants.rotations_all}
eval_env_interface_class: ${monty.class:tbp.monty.experiment.environment.OneObjectPerEpisodeInterface}
