# @package experiment.config

do_eval: true
eval_env_interface_class: ${monty.class:tbp.monty.experiment.environment.OneObjectPerEpisodeInterface}
eval_env_interface_args:
  parent_to_child_mapping: null
  object_init_sampler:
    _target_: tbp.monty.frameworks.environments.object_init_samplers.Predefined
    rotations:
    - - 0.0
      - 30.0
      - 0.0
    - - 0.0
      - 60.0
      - 0.0
    - - 0.0
      - 90.0
      - 0.0
  object_names:
  - capsule3DSolid
  - cubeSolid
