# @package experiment.config

do_eval: true
eval_env_interface_class: ${monty.class:tbp.monty.experiment.environment.OneObjectPerEpisodeInterface}
eval_env_interface_args:
  object_init_sampler:
    _target_: tbp.monty.frameworks.environments.object_init_samplers.Predefined
  object_names:
  - capsule3DSolid
