# @package experiment.config

do_train: true
train_env_interface_class: ${monty.class:tbp.monty.experiment.environment.OneObjectPerEpisodeInterface}
train_env_interface_args:
  parent_to_child_mapping: null
  object_init_sampler:
    _target_: tbp.monty.frameworks.environments.object_init_samplers.Predefined
  object_names:
  - cubeSolid
  - capsule3DSolid

do_eval: true
eval_env_interface_class: ${monty.class:tbp.monty.experiment.environment.OneObjectPerEpisodeInterface}
eval_env_interface_args:
  object_names:
    targets_list:
    - cubeSolid
    source_object_list:
    - cubeSolid
    - capsule3DSolid
    num_distractors: 10
  object_init_sampler:
    _target_: tbp.monty.frameworks.environments.object_init_samplers.Predefined
    positions:
    - ${np.array:[0.2, 1.5, -0.2]}
