# @package experiment.config

do_train: true
train_env_interface_class: ${monty.class:tbp.monty.experiment.environment.OneObjectPerEpisodeInterface}
train_env_interface_args:
  parent_to_child_mapping: null
  object_init_sampler:
    _target_: tbp.monty.frameworks.environments.object_init_samplers.Predefined
    rotations:
    - - 0
      - 0
      - 0
  object_names:
  - capsule3DSolid

