# @package experiment.config

do_train: true
train_env_interface_args:
  parent_to_child_mapping: null
  object_names:
  - numenta_mug
  - terracotta_mug
  - montys_brain
  - montys_heart
  - ramen_pack
  - kashmiri_chilli
  - chip_pack
  - harissa_oil
  - cocktail_bitters
  - cocktail_bible
  - thousand_brains_jp
  - hot_sauce
  object_init_sampler:
    _target_: tbp.monty.frameworks.environments.object_init_samplers.Predefined
    rotations: ${constants.rotations_all}
train_env_interface_class: ${monty.class:tbp.monty.experiment.environment.OneObjectPerEpisodeInterface}
