# @package experiment.config

do_train: true
train_env_interface_args:
  parent_to_child_mapping: null
  object_names:
  - 011_cylinder
  - 016_sphere
  - 023_mug
  object_init_sampler:
    _target_: tbp.monty.frameworks.environments.object_init_samplers.Predefined
    rotations: ${constants.rotations_all}
train_env_interface_class: ${monty.class:tbp.monty.experiment.environment.OneObjectPerEpisodeInterface}
