# @package experiment.config

do_eval: true
eval_env_interface_args:
  parent_to_child_mapping: null
  object_names:
  - mug
  - banana
  object_init_sampler:
    _target_: tbp.monty.frameworks.environments.object_init_samplers.Predefined
    rotations:
    - ${np.array:[0, 15, 30]}
eval_env_interface_class: ${monty.class:tbp.monty.experiment.environment.OneObjectPerEpisodeInterface}
