# @package experiment.config.environment

env_init_args:
  data_path: ${path.expanduser:${oc.env:MONTY_DATA}/mujoco/objects/ycb}
  agents:
    - _target_: tbp.monty.simulators.mujoco.agents.DistantAgent
      _partial_: true
      agent_id: agent_id_0
      sensor_configs:
        patch:
          _target_: tbp.monty.frameworks.sensors.SensorConfig
          resolution:
            width: 64
            height: 64
          zoom: 10.0
        view_finder:
          _target_: tbp.monty.frameworks.sensors.SensorConfig
          resolution:
            width: 64
            height: 64
          zoom: 1.0
      position:
        - 0.0
        - 1.5
        - 0.2
  raise_actuate_missing: false
env_init_func: ${monty.class:tbp.monty.simulators.mujoco.MuJoCoSimulator}
