# @package experiment.config.environment

env_init_args:
  agents:
    - _target_: tbp.monty.simulators.mujoco.agents.NoopAgent
      _partial_: true
      agent_id: agent_id_0
      sensor_configs:
        sensor_id_0:
          _target_: tbp.monty.frameworks.sensors.SensorConfig
          resolution:
            width: 320
            height: 240
  raise_actuate_missing: false
env_init_func: ${monty.class:tbp.monty.simulators.mujoco.MuJoCoSimulator}
