# @package experiment.config.logging

monty_log_level: BASIC
monty_handlers:
- ${monty.class:tbp.monty.frameworks.loggers.monty_handlers.BasicCSVStatsHandler}
wandb_handlers:
- ${monty.class:tbp.monty.frameworks.loggers.wandb_handlers.BasicWandbTableStatsHandler}
- ${monty.class:tbp.monty.frameworks.loggers.wandb_handlers.BasicWandbChartStatsHandler}
python_log_level: WARNING
python_log_to_file: true
python_log_to_stderr: true
output_dir: ${path.expanduser:${oc.env:MONTY_LOGS}/projects/monty_runs}
resume_wandb_run: false
wandb_id:
  _target_: wandb.util.generate_id
wandb_group: benchmark_experiments
