# @package experiment.config.monty_config.motor_system_config

defaults:
  - policy: test_predefined_supervised_training_actions
  - policy_selector: single_policy_selector

_target_: tbp.monty.frameworks.models.motor_system.MotorSystem
