# @package experiment.config.monty_config.learning_modules

learning_module_0:
  _target_: tbp.monty.frameworks.models.displacement_matching.DisplacementGraphLM
  k: 10
  match_attribute: displacement
  tolerance: ${np.array:[0.0001, 0.0001, 0.0001]}
  graph_delta_thresholds:
    patch:
      distance: 0.01
      pose_vectors: ${np.list_eval:[np.pi / 8, np.pi * 2, np.pi * 2]}
      principal_curvatures_log:
      - 1.0
      - 1.0
      hsv:
      - 0.1
      - 1
      - 1
