# @package experiment.config.monty_config.learning_modules

learning_module_0:
  _target_: tbp.monty.frameworks.models.evidence_matching.learning_module.EvidenceGraphLM
  max_match_distance: 0.001
  tolerances:
    patch_0:
      hsv: ${np.array:[0.1, 1, 1]}
      principal_curvatures_log: ${np.ones:2}
  feature_weights: {}
  max_graph_size: 0.3
  num_model_voxels_per_dim: 200
  max_nodes_per_graph: 2000
  object_evidence_threshold: 1
  hypotheses_updater_class: ${monty.class:tbp.monty.frameworks.models.evidence_matching.burst_sampling.BurstSamplingHypothesesUpdater}
  evidence_threshold_config: all
  gsg:
    _target_: tbp.monty.frameworks.models.goal_generation.EvidenceGoalGenerator
    goal_tolerances:
      location: 0.15
    elapsed_steps_factor: 10
    min_post_goal_success_steps: 20
    x_percent_scale_factor: 0.75
    desired_object_distance: 0.03
    wait_growth_multiplier: 1
learning_module_1:
  _target_: tbp.monty.frameworks.models.evidence_matching.learning_module.EvidenceGraphLM
  max_match_distance: 0.001
  tolerances:
    patch_1:
      hsv: ${np.array:[0.1, 1, 1]}
      principal_curvatures_log: ${np.ones:2}
    learning_module_0:
      object_id: 1
  feature_weights:
    learning_module_0:
      object_id: 1
  max_graph_size: 0.4
  num_model_voxels_per_dim: 200
  max_nodes_per_graph: 2000
