# @package experiment.config.monty_config.learning_modules
        
learning_module_0:
  _target_: tbp.monty.frameworks.models.evidence_matching.learning_module.EvidenceGraphLM
  tolerances:
    patch:
      hsv: ${np.array:[0.1, 0.2, 0.2]}
      principal_curvatures_log: ${np.ones:2}
  feature_weights:
    patch:
      hsv: ${np.array:[2, 0.5, 0.5]}
      pose_vectors: ${np.ones:3}
      principal_curvatures_log: ${np.ones:2}
  max_match_distance: 0.01
  x_percent_threshold: 50
  graph_delta_thresholds:
    patch:
      distance: 0.01
      pose_vectors: ${np.list_eval:[np.pi / 8, np.pi * 2, np.pi * 2]}
      principal_curvatures_log:
      - 1.0
      - 1.0
      hsv:
      - 0.1
      - 1
      - 1
  object_evidence_threshold: 100
  required_symmetry_evidence: 20
  hypotheses_updater_args:
    max_nneighbors: 5
