# @package experiment.config.monty_config.learning_modules

learning_module_0:
  _target_: tbp.monty.frameworks.models.evidence_matching.learning_module.EvidenceGraphLM
  max_match_distance: 5
  tolerances:
    patch:
      principal_curvatures_log: ${np.ones:2}
      pose_vectors: ${np.array:[45, 45, 45]}
  feature_weights:
    patch:
      pose_vectors:
      - 0
      - 1
      - 0
  hypotheses_updater_args:
    initial_possible_poses:
    - - 0
      - 0
      - 0
