# @package experiment.config.monty_config.learning_modules

learning_module_0:
  _target_: tbp.monty.frameworks.models.feature_location_matching.FeatureGraphLM
  max_match_distance: None
  tolerances:
    patch: {}
