# @package experiment.config.monty_config.learning_modules

learning_module_0:
  _target_: tbp.monty.frameworks.models.evidence_matching.learning_module.EvidenceGraphLM
  max_match_distance: 0.001
  feature_weights:
    patch:
      hsv: ${np.array:[1, 0, 0]}
  hypotheses_updater_args:
    initial_possible_poses:
    - - 0
      - 0
      - 0
    - - 45
      - 0
      - 0
    - - 90
      - 0
      - 0
  tolerances:
    patch:
      hsv: ${np.array:[0.1, 1, 1]}
      principal_curvatures_log: ${np.ones:2}
