# @package experiment.config.monty_config.learning_modules

learning_module_0:
  _target_: tbp.monty.frameworks.models.feature_location_matching.FeatureGraphLM
  max_match_distance: 0.01
  tolerances:
    patch:
      on_object: 0
      rgba:
      - 10
      - 10
      - 10
      - 10
      principal_curvatures:
      - 5
      - 5
      pose_vectors: ${np.list_eval:[0.7, np.pi * 2, np.pi * 2]}
