# @package experiment.config.monty_config.learning_modules

learning_module_0:
  _target_: tbp.monty.frameworks.models.evidence_matching.learning_module.EvidenceGraphLM
  feature_weights:
    patch:
      hsv: ${np.array:[1, 0, 0]}
  tolerances:
    patch:
      hsv: ${np.array:[0.1, 1, 1]}
      principal_curvatures_log: ${np.ones:2}
  max_match_distance: 0.001
  hypotheses_updater_class: ${monty.class:tbp.monty.frameworks.models.evidence_matching.burst_sampling.BurstSamplingHypothesesUpdater}
