# @package experiment.config.monty_config.learning_modules

learning_module_0:
  _target_: tbp.monty.frameworks.models.no_reset_evidence_matching.NoResetEvidenceGraphLM
  max_match_distance: 0.001
  tolerances:
    patch:
      hsv:
      - 0.1
      - 1
      - 1
      principal_curvatures_log:
      - 1
      - 1
  feature_weights:
    patch:
      hsv:
      - 1
      - 0
      - 0
