# @package experiment.config.monty_config.learning_modules

learning_module_0:
  _target_: tbp.monty.frameworks.models.feature_location_matching.FeatureGraphLM
  max_match_distance: 0.01
  tolerances:
    patch:
      hsv:
      - 0.1
      - 1
      - 1
      principal_curvatures_log:
      - 0.1
      - 0.1
  initial_possible_poses: uniform
