# @package experiment.config.monty_config.learning_modules

learning_module_0:
  _target_: tbp.monty.frameworks.models.evidence_matching.learning_module.EvidenceGraphLM
  tolerances:
    patch:
      pose_vectors: ${np.array:[20, 20, 20]}
  feature_weights: {}
  max_match_distance: 0.001
