# @package experiment.config.monty_config.learning_modules

learning_module_0:
  _target_: tbp.monty.frameworks.models.evidence_matching.learning_module.EvidenceGraphLM
  max_match_distance: 0.01
  evidence_threshold_config: 80%
  x_percent_threshold: 20
  gsg:
    _target_: tbp.monty.frameworks.models.goal_generation.EvidenceGoalGenerator
    goal_tolerances:
      location: 0.015
    min_post_goal_success_steps: 5
  hypotheses_updater_args:
    max_nneighbors: 10
  feature_weights:
    patch_0:
      hsv: ${np.array:[1, 0.5, 0.5]}
  tolerances:
    patch_0:
      hsv: ${np.array:[0.1, 0.2, 0.2]}
      principal_curvatures_log: ${np.ones:2}
learning_module_1:
  _target_: tbp.monty.frameworks.models.evidence_matching.learning_module.EvidenceGraphLM
  max_match_distance: 0.01
  evidence_threshold_config: 80%
  x_percent_threshold: 20
  gsg:
    _target_: tbp.monty.frameworks.models.goal_generation.EvidenceGoalGenerator
    goal_tolerances:
      location: 0.015
    min_post_goal_success_steps: 5
  hypotheses_updater_args:
    max_nneighbors: 10
  feature_weights:
    patch_1:
      hsv: ${np.array:[1, 0.5, 0.5]}
  tolerances:
    patch_1:
      hsv: ${np.array:[0.1, 0.2, 0.2]}
      principal_curvatures_log: ${np.ones:2}
learning_module_2:
  _target_: tbp.monty.frameworks.models.evidence_matching.learning_module.EvidenceGraphLM
  max_match_distance: 0.01
  evidence_threshold_config: 80%
  x_percent_threshold: 20
  gsg:
    _target_: tbp.monty.frameworks.models.goal_generation.EvidenceGoalGenerator
    goal_tolerances:
      location: 0.015
    min_post_goal_success_steps: 5
  hypotheses_updater_args:
    max_nneighbors: 10
  feature_weights:
    patch_2:
      hsv: ${np.array:[1, 0.5, 0.5]}
  tolerances:
    patch_2:
      hsv: ${np.array:[0.1, 0.2, 0.2]}
      principal_curvatures_log: ${np.ones:2}
learning_module_3:
  _target_: tbp.monty.frameworks.models.evidence_matching.learning_module.EvidenceGraphLM
  max_match_distance: 0.01
  evidence_threshold_config: 80%
  x_percent_threshold: 20
  gsg:
    _target_: tbp.monty.frameworks.models.goal_generation.EvidenceGoalGenerator
    goal_tolerances:
      location: 0.015
    min_post_goal_success_steps: 5
  hypotheses_updater_args:
    max_nneighbors: 10
  feature_weights:
    patch_3:
      hsv: ${np.array:[1, 0.5, 0.5]}
  tolerances:
    patch_3:
      hsv: ${np.array:[0.1, 0.2, 0.2]}
      principal_curvatures_log: ${np.ones:2}
learning_module_4:
  _target_: tbp.monty.frameworks.models.evidence_matching.learning_module.EvidenceGraphLM
  max_match_distance: 0.01
  evidence_threshold_config: 80%
  x_percent_threshold: 20
  gsg:
    _target_: tbp.monty.frameworks.models.goal_generation.EvidenceGoalGenerator
    goal_tolerances:
      location: 0.015
    min_post_goal_success_steps: 5
  hypotheses_updater_args:
    max_nneighbors: 10
  feature_weights:
    patch_4:
      hsv: ${np.array:[1, 0.5, 0.5]}
  tolerances:
    patch_4:
      hsv: ${np.array:[0.1, 0.2, 0.2]}
      principal_curvatures_log: ${np.ones:2}
