name: Triage
on:
  pull_request_target:
    branches:
    - main
    types:
    - opened
    - edited

jobs:
  pr_title_triage:
    name: pr-title-triage
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title format
        env:
          # Store in an environment variable to prevent trying to
          # run backticked strings in the title.
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          set -e

          pattern="^(build|chore|ci|docs|feat|fix|perf|refactor|revert|rfc|style|test)!?:.+"
          if [[ ! $PR_TITLE =~ $pattern ]]; then
            echo "This PR title is missing a Conventional Commits label."
            echo "A maintainer will update it appropriately during triage."
            echo "See https://thousandbrainsproject.readme.io/docs/triage#title-1"
            exit 1
          fi

          pattern="^(test|docs)!:.+"
          if [[ $PR_TITLE =~ $pattern ]]; then
            echo "This PR title indicates it is only changing tests or documentation, and"
            echo "that those changes are breaking changes. Changes that"
            echo "only change files in 'tests' or 'docs' cannot produce breaking"
            echo "changes."
            echo "  If this PR has non-test or non-docs changes, then 'test' or 'docs' is not the"
            echo "correct label for this PR."
            exit 1
          fi
